set D=breathless_parks
mkdir %D%
copy breathless_parks.exe %D%\breathless_parks.exe
copy armchair.png %D%\armchair.png
copy back_music.wav %D%\back_music.wav
copy back_tiles.png %D%\back_tiles.png
copy bird_left_down.png %D%\bird_left_down.png
copy bird_left_up.png %D%\bird_left_up.png
copy bird_right_down.png %D%\bird_right_down.png
copy bird_right_up.png %D%\bird_right_up.png
copy bird1.wav %D%\bird1.wav
copy bird2.wav %D%\bird2.wav
copy bird3.wav %D%\bird3.wav
copy bird4.wav %D%\bird4.wav
copy blink.png %D%\blink.png
copy closed_door.png %D%\closed_door.png
copy couch.png %D%\couch.png
copy couch_back.png %D%\couch_back.png
copy grays_anatomy.wav %D%\grays_anatomy.wav
copy hit_table.wav %D%\hit_table.wav
copy instruction_left.png %D%\instruction_left.png
copy instruction_right.png %D%\instruction_right.png
copy matlock.wav %D%\matlock.wav
copy nurse.wav %D%\nurse.wav
copy nurse1.png %D%\nurse1.png
copy nurse2.png %D%\nurse2.png
copy nurse3.png %D%\nurse3.png
copy old_broad_talk_mouth.png %D%\old_broad_talk_mouth.png
copy old_guy.png %D%\old_guy.png
copy old_guy_sitting.png %D%\old_guy_sitting.png
copy old_guy_sitting_blink.png %D%\old_guy_sitting_blink.png
copy old_guy_win.png %D%\old_guy_win.png
copy old_guy1.png %D%\old_guy1.png
copy old_guy2.png %D%\old_guy2.png
copy old_guy3.png %D%\old_guy3.png
copy other_dude_mouth_talks.png %D%\other_dude_mouth_talks.png
copy other_dude_sitting.png %D%\other_dude_sitting.png
copy other_dude_winning.png %D%\other_dude_winning.png
copy other_dude1.png %D%\other_dude1.png
copy other_dude2.png %D%\other_dude2.png
copy other_dude3.png %D%\other_dude3.png
copy other_guy_wins.wav %D%\other_guy_wins.wav
copy outside.png %D%\outside.png
copy painting1.png %D%\painting1.png
copy painting2.png %D%\painting2.png
copy shut_mouth.png %D%\shut_mouth.png
copy sleeping_woman.png %D%\sleeping_woman.png
copy space_big.png %D%\space_big.png
copy space_small.png %D%\space_small.png
copy squeak.wav %D%\squeak.wav
copy table.png %D%\table.png
copy table_empty.png %D%\table_empty.png
copy tv.png %D%\tv.png
copy win.wav %D%\win.wav
copy woman1.png %D%\woman1.png
copy woman2.png %D%\woman2.png
copy woman3.png %D%\woman3.png